### ISSUE TITLE
Code doesn't compile?

### ISSUE THREAD

**Issue by MarenFayre** [rebelroad-reinhart/brickmap-vulkan#1]
I have VulkanSDK 1.3.211.0 installed, any idea what this error means?
```
cmake .
VS022 > Build  > Build solution
```

Build started...
1>------ Build started: Project: shaders, Configuration: Debug x64 ------
2>------ Build started: Project: rebel_engine, Configuration: Debug x64 ------
2>cmake_pch.cxx
2>app.cpp
2>vulkan_app.cpp
2>imgui_context.cpp
2>camera.cpp
2>ray_tracer.cpp
2>world.cpp
2>buffer.cpp
2>cache_keys.cpp
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::RenderPassCreateFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::RenderPassCreateFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::RenderPassCreateFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::RenderPassCreateFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::RenderPassCreateFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\cache_keys.cpp(17): message : see reference to function template instantiation 'void hash_combine<vk::RenderPassCreateFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::RenderPassCreateFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(7,10): error C2064: term does not evaluate to a function taking 1 arguments
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::AttachmentDescriptionFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::AttachmentDescriptionFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::AttachmentDescriptionFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::AttachmentDescriptionFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::AttachmentDescriptionFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\cache_keys.cpp(23): message : see reference to function template instantiation 'void hash_combine<vk::AttachmentDescriptionFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::AttachmentDescriptionFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::SubpassDescriptionFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::SubpassDescriptionFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::SubpassDescriptionFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::SubpassDescriptionFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::SubpassDescriptionFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\cache_keys.cpp(38): message : see reference to function template instantiation 'void hash_combine<vk::SubpassDescriptionFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::SubpassDescriptionFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::PipelineStageFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::PipelineStageFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::PipelineStageFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::PipelineStageFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::PipelineStageFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\cache_keys.cpp(89): message : see reference to function template instantiation 'void hash_combine<vk::PipelineStageFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::PipelineStageFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::AccessFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::AccessFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::AccessFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::AccessFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::AccessFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\cache_keys.cpp(91): message : see reference to function template instantiation 'void hash_combine<vk::AccessFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::AccessFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::DependencyFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::DependencyFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::DependencyFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::DependencyFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::DependencyFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\cache_keys.cpp(93): message : see reference to function template instantiation 'void hash_combine<vk::DependencyFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::DependencyFlags
2>        ]
2>descriptors.cpp
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::ShaderStageFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::ShaderStageFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::ShaderStageFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::ShaderStageFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::ShaderStageFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\descriptors.cpp(235): message : see reference to function template instantiation 'void hash_combine<vk::ShaderStageFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::ShaderStageFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(7,10): error C2064: term does not evaluate to a function taking 1 arguments
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\hash/hash_utils.h(6): error C2280: 'std::hash<T>::hash(void)': attempting to reference a deleted function
2>        with
2>        [
2>            T=vk::DescriptorBindingFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120): message : compiler has generated 'std::hash<T>::hash' here
2>        with
2>        [
2>            T=vk::DescriptorBindingFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2120,1): message : 'std::hash<T>::hash(void)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)'
2>        with
2>        [
2>            T=vk::DescriptorBindingFlags
2>        ]
2>        and
2>        [
2>            _Kty=vk::DescriptorBindingFlags
2>        ]
2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\type_traits(2105,5): message : 'std::_Conditionally_enabled_hash<_Kty,false>::_Conditionally_enabled_hash(void)': function was explicitly deleted
2>        with
2>        [
2>            _Kty=vk::DescriptorBindingFlags
2>        ]
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\descriptors.cpp(236): message : see reference to function template instantiation 'void hash_combine<vk::DescriptorBindingFlags>(size_t &,const T &)' being compiled
2>        with
2>        [
2>            T=vk::DescriptorBindingFlags
2>        ]
2>device_context.cpp
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\device_context.cpp(141,66): error C2664: 'vkb::PhysicalDeviceSelector &vkb::PhysicalDeviceSelector::set_required_features(const VkPhysicalDeviceFeatures &)': cannot convert argument 1 from 'const vk::PhysicalDeviceFeatures' to 'const VkPhysicalDeviceFeatures &'
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\device_context.cpp(141,66): message : Reason: cannot convert from 'const vk::PhysicalDeviceFeatures' to 'const VkPhysicalDeviceFeatures'
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\device_context.cpp(141,47): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>C:\Users\user\Downloads\brickmap-vulkan-main\_deps\vk-bootstrap-src\src\VkBootstrap.h(595,26): message : see declaration of 'vkb::PhysicalDeviceSelector::set_required_features'
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\device_context.cpp(142,72): error C2664: 'vkb::PhysicalDeviceSelector &vkb::PhysicalDeviceSelector::set_required_features_12(VkPhysicalDeviceVulkan12Features)': cannot convert argument 1 from 'const vk::PhysicalDeviceVulkan12Features' to 'VkPhysicalDeviceVulkan12Features'
2>C:\Users\user\Downloads\brickmap-vulkan-main\code\modules\engine\vulkan\device_context.cpp(142,50): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>C:\Users\user\Downloads\brickmap-vulkan-main\_deps\vk-bootstrap-src\src\VkBootstrap.h(602,26): message : see declaration of 'vkb::PhysicalDeviceSelector::set_required_features_12'
2>frame.cpp
2>image.cpp
2>initializers.cpp
2>pipeline_builder.cpp
2>push_buffer.cpp
2>render_context.cpp
2>render_pass_builder.cpp
2>sampler.cpp
2>shader.cpp
2>worker.cpp
2>Generating Code...
2>Done building project "rebel_engine.vcxproj" -- FAILED.
3>------ Build started: Project: brickmap-vulkan, Configuration: Debug x64 ------
3>LINK : fatal error LNK1104: cannot open file '..\..\modules\engine\Debug\rebel_engine.lib'
3>Done building project "brickmap-vulkan.vcxproj" -- FAILED.
========== Build: 1 succeeded, 2 failed, 9 up-to-date, 0 skipped ==========

**Comment by rebelroad-reinhart** [comment]
What compiler are you using?

**Comment by rebelroad-reinhart** [comment]
Looks like something I'm doing with hashes that isn't compatible with your compiler or std lib implementation. I will investigate it and fix.

**Comment by rebelroad-reinhart** [comment]
Fixes submitted. I wasn't including vulkan_hash correctly re: the new SDK. I also was not providing an explicit conversion on physical device features init that is now required.

**Comment by MarenFayre** [comment]
That fixed it, thank you!
